# Dockerfile? instruções para uma imagem

FROM alpine:3.14
CMD ["echo", "Eu sou uma estudante da Trybe! :>"]

#FROM baseImage
#Vamos começar a construção desta imagem se baseando na imagem já existente, chamada alpine, com a tag 3.14
#CMD [ "executable" ]

# docker build <flags> -t <nome-da-imagem> <contexto/dockerfile>
# docker run --rm primeira-imagem
