version: '3'
services:
  site:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__database: site
      database__connection__host: db
      database__connection__user: root
      database__connection__password: senha
    depends_on:
      - "db"
    restart: always
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: senha