FROM chuanwen/cowsay
# ENTRYPOINT [ "executable" ]
ENTRYPOINT [ "/usr/games/cowsay" ]
# CMD [ "executable" ]
CMD [ "muuuh" ]

#docker build -t cowsay . //build container
#docker run cowsay //run image

#docker container run cowsay -l
#docker container run cowsay -f dragon-and-cow "VQV TRYBE"
#docker container run cowsay -f vader-koala I AM YOUR KOALA